[tool.poetry]
name = "ezrules"
version = "0.6.0"
description = ""
authors = ["Konstantin Sofeikov <sofeykov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"
flask-wtf = "*"
bootstrap-flask = "*"
pyyaml = "*"
"ruamel.yaml" = "*"
gunicorn = "*"
sphinx = "*"
pyparsing = "*"
sqlalchemy = "*"
flask-security-too = {extras = ["common"], version = "*"}
psycopg2-binary = "*"
pytz = "*"
email-validator = "*"
sqlalchemy-utils = "*"
click = "^8.0.0"
pydantic-settings = "^2.3.3"
pydantic = "^2.7.4"

[tool.poetry.group.test.dependencies]
pytest-cov = "*"
pytest = "*"
coverage = "*"

[tool.poetry.scripts]
ezrules = "ezrules.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
